image: python:3.10

stages:
  - test

robot_tests:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - robot -d reports tests
  artifacts:
    when: always
    paths:
      - reports/
    expire_in: 1 week